apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - victoria-metrics.yaml
  - victoria-logs.yaml
  - tempo.yaml
  - otel-collector.yaml
  - pyroscope.yaml
  - grafana.yaml
  - ../../grafana
labels:
  - pairs:
      app.kubernetes.io/part-of: observability
    includeSelectors: false
