// GENERATED by mobile/tool/theme.dart from ../ui/finances/src/app/globals.css. Do not edit;
// change the CSS and run `mise run mobile:gen`.
// ignore_for_file: type=lint

import 'dart:ui' show Color;

/// The kit's colour tokens, one scheme: light or dark.
class TokenColors {
  const TokenColors({
    required this.card,
    required this.cardForeground,
    required this.popover,
    required this.popoverForeground,
    required this.primary,
    required this.primaryForeground,
    required this.secondary,
    required this.secondaryForeground,
    required this.muted,
    required this.mutedForeground,
    required this.accent,
    required this.accentForeground,
    required this.destructive,
    required this.destructiveForeground,
    required this.border,
    required this.input,
    required this.ring,
    required this.chart1,
    required this.chart2,
    required this.chart3,
    required this.chart4,
    required this.chart5,
    required this.sidebar,
    required this.background,
    required this.foreground,
    required this.priority1,
    required this.priority2,
    required this.priority3,
    required this.priority4,
    required this.success,
    required this.warning,
  });

  final Color card;
  final Color cardForeground;
  final Color popover;
  final Color popoverForeground;
  final Color primary;
  final Color primaryForeground;
  final Color secondary;
  final Color secondaryForeground;
  final Color muted;
  final Color mutedForeground;
  final Color accent;
  final Color accentForeground;
  final Color destructive;
  final Color destructiveForeground;
  final Color border;
  final Color input;
  final Color ring;
  final Color chart1;
  final Color chart2;
  final Color chart3;
  final Color chart4;
  final Color chart5;
  final Color sidebar;
  final Color background;
  final Color foreground;
  final Color priority1;
  final Color priority2;
  final Color priority3;
  final Color priority4;
  final Color success;
  final Color warning;
}

/// `:root` of the sheet.
const lightTokens = TokenColors(
  card: Color(0xFFFFFFFF),
  cardForeground: Color(0xFF0A0A0A),
  popover: Color(0xFFFFFFFF),
  popoverForeground: Color(0xFF0A0A0A),
  primary: Color(0xFF171717),
  primaryForeground: Color(0xFFFAFAFA),
  secondary: Color(0xFFF5F5F5),
  secondaryForeground: Color(0xFF171717),
  muted: Color(0xFFF5F5F5),
  mutedForeground: Color(0xFF737373),
  accent: Color(0xFFF5F5F5),
  accentForeground: Color(0xFF171717),
  destructive: Color(0xFFE7000B),
  destructiveForeground: Color(0xFFF8FAFC),
  border: Color(0xFFE5E5E5),
  input: Color(0xFFE5E5E5),
  ring: Color(0xFFA1A1A1),
  chart1: Color(0xFF8EC5FF),
  chart2: Color(0xFF2B7FFF),
  chart3: Color(0xFF155DFC),
  chart4: Color(0xFF1447E6),
  chart5: Color(0xFF193CB8),
  sidebar: Color(0xFFFAFAFA),
  background: Color(0xFFFFFFFF),
  foreground: Color(0xFF0A0A0A),
  priority1: Color(0xFFE7000B),
  priority2: Color(0xFFF76C00),
  priority3: Color(0xFFE3A300),
  priority4: Color(0xFF737373),
  success: Color(0xFF008B45),
  warning: Color(0xFFE3A300),
);

/// `.dark` of the sheet, with what it inherits from `:root`.
const darkTokens = TokenColors(
  card: Color(0xFF171717),
  cardForeground: Color(0xFFFAFAFA),
  popover: Color(0xFF171717),
  popoverForeground: Color(0xFFFAFAFA),
  primary: Color(0xFFE5E5E5),
  primaryForeground: Color(0xFF171717),
  secondary: Color(0xFF262626),
  secondaryForeground: Color(0xFFFAFAFA),
  muted: Color(0xFF262626),
  mutedForeground: Color(0xFFA1A1A1),
  accent: Color(0xFF262626),
  accentForeground: Color(0xFFFAFAFA),
  destructive: Color(0xFFFF6467),
  destructiveForeground: Color(0xFFF8FAFC),
  border: Color(0x1AFFFFFF),
  input: Color(0x26FFFFFF),
  ring: Color(0xFF737373),
  chart1: Color(0xFF8EC5FF),
  chart2: Color(0xFF2B7FFF),
  chart3: Color(0xFF155DFC),
  chart4: Color(0xFF1447E6),
  chart5: Color(0xFF193CB8),
  sidebar: Color(0xFF171717),
  background: Color(0xFF0A0A0A),
  foreground: Color(0xFFFAFAFA),
  priority1: Color(0xFFFF6467),
  priority2: Color(0xFFFF893B),
  priority3: Color(0xFFE9B928),
  priority4: Color(0xFFA1A1A1),
  success: Color(0xFF2EC18C),
  warning: Color(0xFFE9B928),
);

/// `--radius` in logical pixels (1rem = 16px), and the steps the sheet derives.
const tokenRadius = 10.0;
const tokenRadiusSm = 6.0;
const tokenRadiusMd = 8.0;
const tokenRadiusLg = 10.0;
const tokenRadiusXl = 14.0;

/// The token names, in the sheet's order.
const tokenNames = <String>[
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'sidebar',
  'background',
  'foreground',
  'priority-1',
  'priority-2',
  'priority-3',
  'priority-4',
  'success',
  'warning',
];
