apiVersion: v1
kind: Service
metadata:
  name: engine
  labels:
    app.kubernetes.io/name: engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: engine
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
