// Renders the Radar's published issues into `src/generated/radar/` so the page
// and each issue's page carry their content in the HTML (search engines, link
// previews and crawlers read the HTML, not what a script fetches later). Runs in
// `pnpm gen` after the lab generator. Only published digests are ever read: the
// public endpoint serves no drafts, and they are filtered here again. When the
// radar cannot be reached (an offline build, a checkout with no cluster) it
// writes an empty list and says so; the page then fetches in the browser as
// before, and the build never fails for want of the network.
//
//   RADAR_SOURCE_URL=https://inorbit.hr node --no-warnings tool/radar-data.ts

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { RadarDigest, RadarIssue } from "../src/lib/radar.ts";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../src/generated/radar");
const source = (process.env.RADAR_SOURCE_URL ?? "https://inorbit.hr").replace(/\/$/, "");

// The service caps one list at 100 digests, so the build asks per language and
// reader language (each well under the cap for now) and says so loudly when a
// list comes back full, since that means weeks were left out.
const CAP = 100;

async function published(): Promise<RadarDigest[]> {
  const all: RadarDigest[] = [];
  try {
    for (const language of ["go", "rust"]) {
      for (const lang of ["en", "hr"]) {
        const res = await fetch(`${source}/v1/radar/digests?language=${language}&lang=${lang}&limit=${CAP}`, {
          headers: { accept: "application/json", "user-agent": "tbd-www-build" },
          signal: AbortSignal.timeout(15_000),
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const body = (await res.json()) as { digests?: RadarDigest[] };
        const got = body.digests ?? [];
        if (got.length >= CAP) {
          console.warn(
            `radar: ${language}/${lang} returned ${got.length}, the service's cap; older weeks are missing until the list pages`,
          );
        }
        all.push(...got);
      }
    }
  } catch (e) {
    console.warn(
      `radar: ${source} not reachable (${(e as Error).message}); no issues rendered, the page fetches in the browser`,
    );
    return [];
  }
  return all.filter((d) => d.status === "published" && !d.stub);
}

const digests = await published();
// Issues are weeks. Only reviewed live weeks are numbered, in order; archive
// weeks (the backfill, not individually reviewed) have pages but no number.
const weeks = [...new Set(digests.map((d) => d.week))].sort();
let n = 0;
const issues: RadarIssue[] = weeks
  .map((week) => {
    const ofWeek = digests.filter((d) => d.week === week);
    const live = ofWeek.some((d) => d.origin !== "archive");
    return { number: live ? ++n : null, week, slug: week.toLowerCase(), digests: ofWeek };
  })
  .reverse();

mkdirSync(out, { recursive: true });
writeFileSync(
  join(out, "index.ts"),
  `// Generated by tool/radar-data.ts from ${source}. Do not edit; run \`pnpm gen\`.
import type { RadarIssue } from "@/lib/radar";

export const issues: RadarIssue[] = ${JSON.stringify(issues, null, 2)};
`,
);
console.log(
  `radar: ${issues.length} issue${issues.length === 1 ? "" : "s"}, ${digests.length} digests -> ${out}`,
);
