apiVersion: v1
kind: ConfigMap
metadata:
  name: tbd-env
data:
  RUST_LOG: info
  LOG_FORMAT: json
  ENGINE_LISTEN_ADDR: 0.0.0.0:50051
  PROTOCOL_LISTEN_ADDR: 0.0.0.0:8080
  PROTOCOL_ENGINE_URL: http://engine:50051
