apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tbd
resources:
  - namespace.yaml
  - configmap.yaml
  - engine
  - protocol
  - ledger
  - envoy
labels:
  - pairs:
      app.kubernetes.io/part-of: tbd
    includeSelectors: false
