// The web kit's design tokens as Dart. Reads the `:root` and `.dark` custom
// properties of ui/finances/src/app/globals.css -- the sheet every web UI in
// this tree carries, byte for byte -- converts each colour to sRGB, and writes
// packages/tbd_ui/lib/src/tokens.g.dart. A phone and a browser then draw from
// one palette, and `mise run mobile:check` fails when the two disagree.
//
//   dart run tool/theme.dart            write tokens.g.dart
//   dart run tool/theme.dart --check    exit 1 if tokens.g.dart is stale
//
// Colour maths: OKLCH -> OKLab -> linear sRGB -> sRGB, from Björn Ottosson's
// reference (bottosson.github.io/posts/oklab), which is what CSS Color 4 uses.
// A value outside the sRGB gamut is clipped per channel, as browsers do for
// `oklch()` today. `hsl()` and an alpha suffix are handled; nothing else in the
// sheet is a colour.
import 'dart:io';
import 'dart:math' as math;

const sheet = '../ui/finances/src/app/globals.css';
const out = 'packages/tbd_ui/lib/src/tokens.g.dart';

void main(List<String> args) {
  final root = Directory.current.path.endsWith('/mobile') ? '.' : 'mobile';
  final css = File('$root/$sheet').readAsStringSync();
  final light = block(css, ':root');
  final dark = block(css, '.dark');
  // Dark inherits what it does not override, as the cascade does.
  final darkFull = {...light, ...dark};
  final names = light.keys
      .where((k) => !k.startsWith('sidebar-') && k != 'radius')
      .toList();
  final missing = names.where((k) => !darkFull.containsKey(k));
  if (missing.isNotEmpty) {
    stderr.writeln('theme: .dark lacks ${missing.join(', ')}');
    exit(1);
  }
  final radius = rem(light['radius']!);
  final b = StringBuffer()
    ..writeln(
      '// GENERATED by mobile/tool/theme.dart from $sheet. Do not edit;',
    )
    ..writeln('// change the CSS and run `mise run mobile:gen`.')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln()
    ..writeln("import 'dart:ui' show Color;")
    ..writeln()
    ..writeln("/// The kit's colour tokens, one scheme: light or dark.")
    ..writeln('class TokenColors {')
    ..writeln('  const TokenColors({')
    ..writeAll(names.map((n) => '    required this.${camel(n)},\n'))
    ..writeln('  });')
    ..writeln()
    ..writeAll(names.map((n) => '  final Color ${camel(n)};\n'))
    ..writeln('}')
    ..writeln()
    ..writeln('/// `:root` of the sheet.')
    ..writeln('const lightTokens = TokenColors(')
    ..writeAll(names.map((n) => '  ${camel(n)}: ${color(light[n]!, n)},\n'))
    ..writeln(');')
    ..writeln()
    ..writeln('/// `.dark` of the sheet, with what it inherits from `:root`.')
    ..writeln('const darkTokens = TokenColors(')
    ..writeAll(names.map((n) => '  ${camel(n)}: ${color(darkFull[n]!, n)},\n'))
    ..writeln(');')
    ..writeln()
    ..writeln(
      '/// `--radius` in logical pixels (1rem = 16px), and the steps the sheet derives.',
    )
    ..writeln('const tokenRadius = $radius;')
    ..writeln('const tokenRadiusSm = ${radius - 4};')
    ..writeln('const tokenRadiusMd = ${radius - 2};')
    ..writeln('const tokenRadiusLg = $radius;')
    ..writeln('const tokenRadiusXl = ${radius + 4};')
    ..writeln()
    ..writeln("/// The token names, in the sheet's order.")
    ..writeln('const tokenNames = <String>[')
    ..writeAll(names.map((n) => "  '$n',\n"))
    ..writeln('];');
  final text = b.toString();
  final file = File('$root/$out');
  if (args.contains('--check')) {
    final current = file.existsSync() ? file.readAsStringSync() : '';
    if (current != text) {
      stderr.writeln(
        'theme: $out is stale against $sheet; run `mise run mobile:gen`',
      );
      exit(1);
    }
    stdout.writeln('theme: ${names.length} tokens, tokens.g.dart is current');
    return;
  }
  file.writeAsStringSync(text);
  stdout.writeln('theme: wrote $out (${names.length} tokens)');
}

/// The `--name: value;` pairs of one selector's block, skipping `var()` refs.
Map<String, String> block(String css, String selector) {
  final start = css.indexOf('\n$selector {');
  if (start < 0) throw StateError('theme: no `$selector` block in the sheet');
  final end = css.indexOf('\n}', start);
  final body = css.substring(start, end);
  final re = RegExp(r'--([a-z0-9-]+):\s*([^;]+);');
  final m = <String, String>{};
  for (final x in re.allMatches(body)) {
    final v = x.group(2)!.trim();
    if (v.startsWith('var(')) continue;
    m[x.group(1)!] = v;
  }
  return m;
}

String camel(String kebab) {
  final parts = kebab.split('-');
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

double rem(String v) {
  final m = RegExp(r'^([0-9.]+)rem$').firstMatch(v);
  if (m == null) throw StateError('theme: radius "$v" is not in rem');
  return double.parse(m.group(1)!) * 16;
}

/// A CSS colour as a Dart `Color(0xAARRGGBB)` literal.
String color(String v, String name) {
  final okl = RegExp(
    r'^oklch\(([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)(?:\s*/\s*([0-9.]+)%?)?\)$',
  ).firstMatch(v);
  final hsl = RegExp(
    r'^hsl\(([0-9.]+)\s+([0-9.]+)%\s+([0-9.]+)%(?:\s*/\s*([0-9.]+)%?)?\)$',
  ).firstMatch(v);
  final (double, double, double) rgb;
  final String? a;
  if (okl != null) {
    rgb = oklchToSrgb(
      double.parse(okl.group(1)!),
      double.parse(okl.group(2)!),
      double.parse(okl.group(3)!),
    );
    a = okl.group(4);
  } else if (hsl != null) {
    rgb = hslToSrgb(
      double.parse(hsl.group(1)!),
      double.parse(hsl.group(2)!) / 100,
      double.parse(hsl.group(3)!) / 100,
    );
    a = hsl.group(4);
  } else {
    throw StateError('theme: "$name: $v" is not a colour this tool reads');
  }
  final (r, g, bl) = rgb;
  final alpha = a == null
      ? 1.0
      : (v.contains('%') && v.contains('/')
            ? double.parse(a) / 100
            : double.parse(a));
  int ch(double x) => (x.clamp(0, 1) * 255).round();
  final hex = (ch(alpha) << 24 | ch(r) << 16 | ch(g) << 8 | ch(bl))
      .toRadixString(16)
      .padLeft(8, '0')
      .toUpperCase();
  return 'Color(0x$hex)';
}

(double, double, double) oklchToSrgb(double l, double c, double hDeg) {
  final h = hDeg * math.pi / 180;
  final a = c * math.cos(h);
  final b = c * math.sin(h);
  // OKLab -> LMS (cube roots) -> linear sRGB.
  final l_ = l + 0.3963377774 * a + 0.2158037573 * b;
  final m_ = l - 0.1055613458 * a - 0.0638541728 * b;
  final s_ = l - 0.0894841775 * a - 1.2914855480 * b;
  final lc = l_ * l_ * l_;
  final mc = m_ * m_ * m_;
  final sc = s_ * s_ * s_;
  final r = 4.0767416621 * lc - 3.3077115913 * mc + 0.2309699292 * sc;
  final g = -1.2684380046 * lc + 2.6097574011 * mc - 0.3413193965 * sc;
  final bl = -0.0041960863 * lc - 0.7034186147 * mc + 1.7076147010 * sc;
  return (gamma(r), gamma(g), gamma(bl));
}

double gamma(double x) {
  final c = x.clamp(0.0, 1.0);
  return c <= 0.0031308 ? 12.92 * c : 1.055 * math.pow(c, 1 / 2.4) - 0.055;
}

(double, double, double) hslToSrgb(double h, double s, double l) {
  double f(double n) {
    final k = (n + h / 30) % 12;
    final a = s * math.min(l, 1 - l);
    return l - a * math.max(-1, math.min(k - 3, math.min(9 - k, 1)));
  }

  return (f(0), f(8), f(4));
}
