// Bundles docs/chaos/scenarios.md and the generated docs/chaos/kinds.md into
// the UI as strings, so the in-app reference is the same file the repo
// documents scenarios and kinds with. Runs before dev, build, lint and
// typecheck (package.json); the output is gitignored.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const docs = resolve(here, "../../../docs/chaos");
const out = resolve(here, "../src/generated/docs.ts");

const scenarios = readFileSync(resolve(docs, "scenarios.md"), "utf8");
const kinds = readFileSync(resolve(docs, "kinds.md"), "utf8");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/gen-docs.mjs from docs/chaos/{scenarios,kinds}.md. Do not edit.\n` +
    `export const scenariosDoc = ${JSON.stringify(scenarios)};\n` +
    `export const kindsDoc = ${JSON.stringify(kinds)};\n`,
);
console.log(`gen-docs: ${scenarios.length} + ${kinds.length} chars from docs/chaos/`);
