// Bundles docs/chaos/scenarios.md into the UI as a string, so the in-app
// reference is the same file the repo documents scenarios with. Runs before
// dev, build, lint and typecheck (package.json); the output is gitignored.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../../../docs/chaos/scenarios.md");
const out = resolve(here, "../src/generated/docs.ts");

const text = readFileSync(src, "utf8");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/gen-docs.mjs from docs/chaos/scenarios.md. Do not edit.\nexport const scenariosDoc = ${JSON.stringify(text)};\n`,
);
console.log(`gen-docs: ${text.length} chars from docs/chaos/scenarios.md`);
